defaults:
  - _self_

experiment: ddm_dino10_simultaneous_diffusion # tag for wandb and log dir

hydra:
  run:
    dir: /media/huang/T7/real_exp/diff_worldmodel/${now:%m%d}_${experiment}_${now:%H%M}
  sweep:
    dir: /media/huang/T7/real_exp/diff_worldmodel/${now:%m%d}_${experiment}_${now:%H%M}
    subdir: ${hydra.job.num}

wandb:
  project: atm_libero
  name: ${now:%m%d}_${experiment}_${now:%H%M}_${hydra:job.num}
  group: ${experiment}

train_gpus: [0]

# Training
lr: 5e-5
batch_size: 12
mix_precision: false
num_workers: 8
val_freq: 5
save_freq: 10
clip_grad: 10.
epochs: 51
seed: 0
dry: false

model_name: TrackTransformer
p_img: 0.5
lbd_track: 10.0
lbd_img: 1.0

dim: 384
dim_head: null
heads: 8
depth: 8

img_size: 128
frame_stack: 4
num_track_ts: 16
num_track_ids: 32
patch_size: 16
track_patch_size: 4

aug_prob: 0.5

train_dataset: ???
val_dataset: ???

optimizer_cfg:
  type: optim.Adam
  params:
    lr: ${lr}
    weight_decay: 0

scheduler_cfg:
  type: CosineAnnealingLRWithWarmup
  params:
    warmup_lr: 1e-5
    warmup_epoch: 5
    T_max: ${epochs}

vae_cfg:
  class_name: ladiwm.model.dino_vae4.AutoencoderKL
  dino_size: [126, 126]
  siglip_size: [144, 144]
  embed_dim: 32
  lossconfig:
    disc_start: 20001
    kl_weight: 0.000001
    disc_weight: 0.5
  enc_config:
    patch_size: 14
    num_register_tokens: 0
    img_size: 526
    init_values: 1.0
    block_chunks: 0
    embed_dim: 768
    pre_weight: /media/huang/T7/ori_mount/pre_weight/dinov2_vitb14_pretrain.pth
  dec_config:
    patch_size: 14
    grid_size: 9
    num_layers: 8
    dim: 256
    num_heads: 8
    out_dim: 3
  ckpt_path:

trans_cfg:
  class_name: ladiwm.model.dit_action_dino5.DiffusionTransformer
  in_channel: 768
  img_size: 81
  down_ratio: 8
  patch_size: 2
  mlp_ratio: 4.0
  n_layers: 12
  dim: 512
  num_heads: 8
  swin_type: 2
  tube_size: 6
#  pretrained_swin: '/media/huang/2da18d46-7cba-4259-9abd-0df819bb104c/pre_weight/swin_base_patch244_window877_kinetics400_22k.pth'

model_cfg:
  class_name: ladiwm.model.ddm_action_dino10.DDM
  load_path: /media/huang/T7/real_exp/diff_worldmodel/0206_ddm_dino10_simultaneous_diffusion_2347/model_best.ckpt
  seq_len: 162
  channels: 768
  transformer_cfg:
    dim: ${dim}
    dim_head: ${dim_head}
    heads: ${heads}
    depth: ${depth}
    attn_dropout: 0.2
    ff_dropout: 0.2
  track_cfg:
    num_track_ts: ${num_track_ts}
    num_track_ids: ${num_track_ids}
    patch_size: ${track_patch_size}
  vid_cfg:
    img_size: ${img_size}
    frame_stack: ${frame_stack}
    patch_size: ${patch_size}
  language_encoder_cfg:
    network_name: MLPEncoder
    input_size: 768
    hidden_size: 128
    num_layers: 1

dataset_cfg:
  img_size: ${img_size}
  frame_stack: ${frame_stack}
  num_track_ts: ${num_track_ts}
  num_track_ids: ${num_track_ids}
  cache_all: false
  cache_image: false
  his_frame: 4
  pred_frame: 6
